### ISSUE TITLE
Problem with AirFlow DAG build_train_deploy job - 503 Getting metadata from plugin failed with error: 'AppAssertionCredentials' object has no attribute 'before_request'

### ISSUE THREAD

**Issue by hejnal** [GoogleCloudPlatform/tensorflow-lifetime-value#3]
I'm experiencing a problem with the DAG execution, something is wrong with the autoML authentication, I have set up the service account (composer), and enable all the permissions, including the autoML.

Any idea?

The error log:

[2019-05-23 10:11:34,368] {models.py:1427} INFO - Executing <Task(PythonOperator): train_automl> on 2019-05-23 10:09:54
[2019-05-23 10:11:34,368] {base_task_runner.py:115} INFO - Running: ['bash', '-c', u'airflow run build_train_deploy train_automl 2019-05-23T10:09:54 --job_id 224 --raw -sd DAGS_FOLDER/01_build_train_deploy.py']
[2019-05-23 10:11:35,731] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:35,731] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2019-05-23 10:11:35,756] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:35,755] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[2019-05-23 10:11:36,478] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:36,478] {__init__.py:45} INFO - Using executor CeleryExecutor
[2019-05-23 10:11:36,509] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:36,509] {configuration.py:389} INFO - Reading the config from /etc/airflow/airflow.cfg
[2019-05-23 10:11:36,534] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:36,533] {app.py:43} WARNING - Using default Composer Environment Variables. Overrides have not been applied.
[2019-05-23 10:11:36,559] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:36,558] {models.py:189} INFO - Filling up the DagBag from /home/airflow/gcs/dags/01_build_train_deploy.py
[2019-05-23 10:11:37,256] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:37,256] {gcp_api_base_hook.py:85} INFO - Getting connection using `gcloud auth` user, since no key file is defined for hook.
[2019-05-23 10:11:37,477] {base_task_runner.py:98} INFO - Subtask: [2019-05-23 10:11:37,476] {_plugin_wrapping.py:83} ERROR - AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f9449a5fe50>" raised exception!
[2019-05-23 10:11:37,478] {base_task_runner.py:98} INFO - Subtask: Traceback (most recent call last):
[2019-05-23 10:11:37,478] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/grpc/_plugin_wrapping.py", line 79, in __call__
[2019-05-23 10:11:37,478] {base_task_runner.py:98} INFO - Subtask:     callback_state, callback))
[2019-05-23 10:11:37,479] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py", line 77, in __call__
[2019-05-23 10:11:37,479] {base_task_runner.py:98} INFO - Subtask:     callback(self._get_authorization_headers(context), None)
[2019-05-23 10:11:37,479] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py", line 61, in _get_authorization_headers
[2019-05-23 10:11:37,480] {base_task_runner.py:98} INFO - Subtask:     self._credentials.before_request(
[2019-05-23 10:11:37,480] {base_task_runner.py:98} INFO - Subtask: AttributeError: 'AppAssertionCredentials' object has no attribute 'before_request'
[2019-05-23 10:11:37,524] {base_task_runner.py:98} INFO - Subtask: Traceback (most recent call last):
[2019-05-23 10:11:37,524] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/bin/airflow", line 7, in <module>
[2019-05-23 10:11:37,525] {base_task_runner.py:98} INFO - Subtask:     exec(compile(f.read(), __file__, 'exec'))
[2019-05-23 10:11:37,525] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/airflow/airflow/bin/airflow", line 27, in <module>
[2019-05-23 10:11:37,525] {base_task_runner.py:98} INFO - Subtask:     args.func(args)
[2019-05-23 10:11:37,526] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/airflow/airflow/bin/cli.py", line 392, in run
[2019-05-23 10:11:37,526] {base_task_runner.py:98} INFO - Subtask:     pool=args.pool,
[2019-05-23 10:11:37,526] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/airflow/airflow/utils/db.py", line 50, in wrapper
[2019-05-23 10:11:37,527] {base_task_runner.py:98} INFO - Subtask:     result = func(*args, **kwargs)
[2019-05-23 10:11:37,528] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/airflow/airflow/models.py", line 1492, in _run_raw_task
[2019-05-23 10:11:37,528] {base_task_runner.py:98} INFO - Subtask:     result = task_copy.execute(context=context)
[2019-05-23 10:11:37,529] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 89, in execute
[2019-05-23 10:11:37,529] {base_task_runner.py:98} INFO - Subtask:     return_value = self.execute_callable()
[2019-05-23 10:11:37,530] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 94, in execute_callable
[2019-05-23 10:11:37,530] {base_task_runner.py:98} INFO - Subtask:     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-05-23 10:11:37,530] {base_task_runner.py:98} INFO - Subtask:   File "/home/airflow/gcs/dags/01_build_train_deploy.py", line 158, in do_train_automl
[2019-05-23 10:11:37,530] {base_task_runner.py:98} INFO - Subtask:     AUTOML_TRAINING_BUDGET)
[2019-05-23 10:11:37,531] {base_task_runner.py:98} INFO - Subtask:   File "/home/airflow/gcs/dags/clv_automl/clv_automl.py", line 56, in create_automl_model
[2019-05-23 10:11:37,532] {base_task_runner.py:98} INFO - Subtask:     {'display_name': dataset_display_name, 'tables_dataset_metadata': {}})
[2019-05-23 10:11:37,533] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/cloud/automl_v1beta1/gapic/auto_ml_client.py", line 347, in create_dataset
[2019-05-23 10:11:37,533] {base_task_runner.py:98} INFO - Subtask:     request, retry=retry, timeout=timeout, metadata=metadata
[2019-05-23 10:11:37,534] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
[2019-05-23 10:11:37,534] {base_task_runner.py:98} INFO - Subtask:     return wrapped_func(*args, **kwargs)
[2019-05-23 10:11:37,534] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
[2019-05-23 10:11:37,535] {base_task_runner.py:98} INFO - Subtask:     on_error=on_error,
[2019-05-23 10:11:37,535] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 179, in retry_target
[2019-05-23 10:11:37,536] {base_task_runner.py:98} INFO - Subtask:     return target()
[2019-05-23 10:11:37,536] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/api_core/timeout.py", line 214, in func_with_timeout
[2019-05-23 10:11:37,537] {base_task_runner.py:98} INFO - Subtask:     return func(*args, **kwargs)
[2019-05-23 10:11:37,537] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
[2019-05-23 10:11:37,538] {base_task_runner.py:98} INFO - Subtask:     six.raise_from(exceptions.from_grpc_error(exc), exc)
[2019-05-23 10:11:37,539] {base_task_runner.py:98} INFO - Subtask:   File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
[2019-05-23 10:11:37,540] {base_task_runner.py:98} INFO - Subtask:     raise value
[2019-05-23 10:11:37,540] {base_task_runner.py:98} INFO - Subtask: google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'AppAssertionCredentials' object has no attribute 'before_request'

**Comment by hejnal** [comment]
Thank you for the fix, it works now.
